# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest
  




steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
# - task: ApplitoolsBuildTask@0
#   displayName: 'Applitools Build Task'
#   inputs:
#     eyesBaseUrl: "https://eyes.applitools.com"
#   env:
#     APPLITOOLS_SERVER_URL: "https://eyes.applitools.com"
 

- script: |
    npm install
    APPLITOOLS_SHOW_LOGS=true npm test
    #npm run build
  displayName: 'npm install and build '
  env:
    APPLITOOLS_API_KEY: $(APPLITOOLS_API_KEY)
    # APPLITOOLS_BATCH_ID: $(System.PullRequest.SourceCommitId)
