jobs:
  build:
    docker:
      - image: circleci/node:8.3.0
      
    working_directory: ~/repo

    steps:
      - checkout:
      - run: export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1`
      - run: printenv