jobs:
  build:
    docker:
      - image: circleci/node:16.13.1
      
    working_directory: ~/repo
    
    steps:
      - run: printenv
      - run:
          command: npm install
      - run:
          name: Prepare for commit push - Temporarily not needed; only want integration on PR
          command: |
            echo $APPLITOOLS_API_KEY
            echo $CIRCLE_BRANCH
      - run:
          name: Set environnment variable and run test
          command: | 
            export APPLITOOLS_BATCH_ID=${CIRCLE_SHA1}
            echo ${APPLITOOLS_BATCH_ID}
            npm test
      
      - run: 
          name: If associated with PR
          command: |
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              echo "This is part of a PR!" 
            else
              echo "This isn't part of a PR!"
            fi
            
