jobs:
  build:
    docker:
      - image: circleci/node:8.3.0
      
    working_directory: ~/repo

    steps:
      - checkout:
      - run: printenv
      - run:
          name: Set enviropnment variable and run test
          command: | 
            export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1` >> $BASH_ENV 
            echo ${APPLITOOLS_BATCH_ID}
            npm install
            npm test