jobs:
  build:
    docker:
      - image: circleci/node:16.13.1
      
    working_directory: ~/repo
    
    steps:
      - checkout:
      - run: printenv
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          command: npm install
       - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Prepare for commit push - Temporarily not needed; only want integration on PR
          command: |
            export APPLITOOLS_PARENT_BRANCH=main
            echo $APPLITOOLS_PARENT_BRANCH
            echo $APPLITOOLS_API_KEY
            echo $CIRCLE_BRANCH
            #curl -L -d '' -X POST "eyesapi.applitools.com/api/externals/github/push?apiKey=$APPLITOOLS_API_KEY&CommitSha=$CIRCLE_SHA1&BranchName=$CIRCLE_BRANCH&ParentBranchName=$APPLITOOLS_PARENT_BRANCH"
      - run:
          name: Set environnment variable and run test
          command: | 
            export APPLITOOLS_BATCH_ID=${CIRCLE_SHA1}
            echo ${APPLITOOLS_BATCH_ID}
            npm test
